# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contactdetails.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.mw = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(303, 510)
        MainWindow.setMinimumSize(QtCore.QSize(303, 510))
        MainWindow.setMaximumSize(QtCore.QSize(303, 510))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.contact_name = QtWidgets.QLabel(self.centralwidget)
        self.contact_name.setGeometry(QtCore.QRect(70, 0, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.contact_name.setFont(font)
        self.contact_name.setText("")
        self.contact_name.setAlignment(QtCore.Qt.AlignCenter)
        self.contact_name.setObjectName("contact_name")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(230, 0, 71, 32))
        self.back_button.setObjectName("back_button")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(0, 0, 71, 32))
        self.submit.setObjectName("submit")
        self.notes = QtWidgets.QTextEdit(self.centralwidget)
        self.notes.setGeometry(QtCore.QRect(110, 240, 181, 81))
        self.notes.setObjectName("notes")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 81, 21))
        self.label_4.setObjectName("label_4")
        self.telephone = QtWidgets.QLineEdit(self.centralwidget)
        self.telephone.setGeometry(QtCore.QRect(110, 120, 181, 22))
        self.telephone.setText("")
        self.telephone.setObjectName("telephone")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 320, 60, 16))
        self.label_8.setObjectName("label_8")
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setGeometry(QtCore.QRect(110, 200, 181, 22))
        self.url.setText("")
        self.url.setObjectName("url")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 81, 21))
        self.label_3.setObjectName("label_3")
        self.first_name = QtWidgets.QLineEdit(self.centralwidget)
        self.first_name.setGeometry(QtCore.QRect(110, 40, 181, 22))
        self.first_name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.first_name.setText("")
        self.first_name.setObjectName("first_name")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 340, 281, 101))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 281, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonListLayout = QtWidgets.QVBoxLayout()
        self.buttonListLayout.setContentsMargins(-1, -1, -1, 0)
        self.buttonListLayout.setObjectName("buttonListLayout")
        self.verticalLayout_2.addLayout(self.buttonListLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 81, 21))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 81, 21))
        self.label.setObjectName("label")
        self.last_name = QtWidgets.QLineEdit(self.centralwidget)
        self.last_name.setGeometry(QtCore.QRect(110, 80, 181, 22))
        self.last_name.setObjectName("last_name")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(110, 160, 181, 22))
        self.email.setText("")
        self.email.setObjectName("email")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 81, 21))
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 81, 21))
        self.label_2.setObjectName("label_2")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(60, 442, 171, 31))
        self.delete_button.setObjectName("delete_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 303, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back_button.setText(_translate("MainWindow", "Back"))
        self.submit.setText(_translate("MainWindow", "Save"))
        self.notes.setPlaceholderText(_translate("MainWindow", "Notes..."))
        self.label_4.setText(_translate("MainWindow", "Telephone:"))
        self.telephone.setPlaceholderText(_translate("MainWindow", "Telphone"))
        self.label_8.setText(_translate("MainWindow", "Tags:"))
        self.url.setPlaceholderText(_translate("MainWindow", "Url"))
        self.label_3.setText(_translate("MainWindow", "E-mail:"))
        self.first_name.setPlaceholderText(_translate("MainWindow", "First Name"))
        self.label_5.setText(_translate("MainWindow", "Url:"))
        self.label.setText(_translate("MainWindow", "First Name:"))
        self.last_name.setPlaceholderText(_translate("MainWindow", "Last Name"))
        self.email.setPlaceholderText(_translate("MainWindow", "E-mail"))
        self.label_6.setText(_translate("MainWindow", "Notes:"))
        self.label_2.setText(_translate("MainWindow", "Last Name:"))
        self.delete_button.setText(_translate("MainWindow", "Delete Contact"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

