# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contactadder.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_textListView(object):
    def setupUi(self, textListView):
        self.tlv = textListView
        textListView.setObjectName("textListView")
        textListView.resize(303, 510)
        textListView.setMinimumSize(QtCore.QSize(303, 510))
        textListView.setMaximumSize(QtCore.QSize(303, 510))
        self.centralwidget = QtWidgets.QWidget(textListView)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(230, 0, 71, 32))
        self.back_button.setObjectName("back_button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 81, 21))
        self.label_2.setObjectName("label_2")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(110, 160, 181, 22))
        self.email.setText("")
        self.email.setObjectName("email")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 81, 21))
        self.label_6.setObjectName("label_6")
        self.first_name = QtWidgets.QLineEdit(self.centralwidget)
        self.first_name.setGeometry(QtCore.QRect(110, 40, 181, 22))
        self.first_name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.first_name.setObjectName("first_name")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 350, 281, 125))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 281, 125))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonListLayout = QtWidgets.QVBoxLayout()
        self.buttonListLayout.setContentsMargins(-1, -1, -1, 0)
        self.buttonListLayout.setObjectName("buttonListLayout")
        self.verticalLayout_2.addLayout(self.buttonListLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 81, 21))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 81, 21))
        self.label.setObjectName("label")
        self.last_name = QtWidgets.QLineEdit(self.centralwidget)
        self.last_name.setGeometry(QtCore.QRect(110, 80, 181, 22))
        self.last_name.setObjectName("last_name")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 81, 21))
        self.label_4.setObjectName("label_4")
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setGeometry(QtCore.QRect(110, 200, 181, 22))
        self.url.setText("")
        self.url.setObjectName("url")
        self.telephone = QtWidgets.QLineEdit(self.centralwidget)
        self.telephone.setGeometry(QtCore.QRect(110, 120, 181, 22))
        self.telephone.setText("")
        self.telephone.setObjectName("telephone")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 332, 60, 16))
        self.label_8.setObjectName("label_8")
        self.notes = QtWidgets.QTextEdit(self.centralwidget)
        self.notes.setGeometry(QtCore.QRect(110, 240, 181, 81))
        self.notes.setObjectName("notes")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setEnabled(False)
        self.submit.setGeometry(QtCore.QRect(0, 0, 71, 32))
        self.submit.setObjectName("submit")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 320, 281, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        textListView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(textListView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 303, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        textListView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(textListView)
        self.statusbar.setObjectName("statusbar")
        textListView.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(textListView)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(textListView)
        QtCore.QMetaObject.connectSlotsByName(textListView)

    def retranslateUi(self, textListView):
        _translate = QtCore.QCoreApplication.translate
        textListView.setWindowTitle(_translate("textListView", "MainWindow"))
        self.label_7.setText(_translate("textListView", "ADD CONTACT:"))
        self.back_button.setText(_translate("textListView", "Back"))
        self.label_2.setText(_translate("textListView", "Last Name:"))
        self.email.setPlaceholderText(_translate("textListView", "E-mail"))
        self.label_6.setText(_translate("textListView", "Notes:"))
        self.first_name.setPlaceholderText(_translate("textListView", "First Name"))
        self.label_5.setText(_translate("textListView", "Url:"))
        self.label_3.setText(_translate("textListView", "E-mail:"))
        self.label.setText(_translate("textListView", "First Name:"))
        self.last_name.setPlaceholderText(_translate("textListView", "Last Name"))
        self.label_4.setText(_translate("textListView", "Telephone:"))
        self.url.setPlaceholderText(_translate("textListView", "URL"))
        self.telephone.setPlaceholderText(_translate("textListView", "Telephone"))
        self.label_8.setText(_translate("textListView", "Tags:"))
        self.notes.setPlaceholderText(_translate("textListView", "Notes..."))
        self.submit.setText(_translate("textListView", "Save"))
        self.menuFile.setTitle(_translate("textListView", "File"))
        self.actionQuit.setText(_translate("textListView", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    textListView = QtWidgets.QMainWindow()
    ui = Ui_textListView()
    ui.setupUi(textListView)
    textListView.show()
    sys.exit(app.exec_())

